### ISSUE TITLE
SmtpException

### ISSUE THREAD

**Issue by GOMTHAA** [AhmerAli1813/Online_Help_Desk#4]
SmtpException: The SMTP server requires a secure connection or the client was not authenticated. The server response was: 5.7.57 Client not authenticated to send mail. Error: 535 5.7.139 Authentication unsuccessful, basic authentication is disabled. [MA0PR01CA0068.INDPRD01.PROD.OUTLOOK.COM 2024-10-15T16:18:27.237Z 08DCECCED383AD48]

When i try to login

**Comment by AhmerAli1813** [comment]
Create new  email Account on outlook  and username passwords 
Path :Services/utilityClasses/EmailSender.cs

    client.Credentials = new NetworkCredential("YourEmailAddress@outlook.com", "YourPasswoard");

**Comment by GOMTHAA** [comment]
![image_2024-10-22_180702010](https://github.com/user-attachments/assets/f375beee-3543-46e4-bb2e-62772da1f344)
U want me to change this into the code u gave?
And create a new outlook email?

**Comment by GOMTHAA** [comment]
I did sir its still showing the same error
![image](https://github.com/user-attachments/assets/bf98c56a-4693-4fbf-90df-7ed249ca827b)
![image](https://github.com/user-attachments/assets/6ce82995-d2bb-46bb-a718-c8c1602f6c26)
![image](https://github.com/user-attachments/assets/7fe11124-b902-4640-a403-10da4b32f6a1)

**Comment by AhmerAli1813** [comment]
Yes, it works!

**Comment by GOMTHAA** [comment]
What to do sir?

**Comment by GOMTHAA** [comment]
Sir??

**Comment by AhmerAli1813** [comment]
Email Sending Issue

Issue: The emailService class is unable to send emails to users, such as
***@***.***, because it lacks the proper authorization. The
credentials for sending emails are not defined within the emailService.

Current Code Snippet:

csharp

Copy code

client.Credentials = new ***@***.***",
"YourPassword");

Steps to Resolve

Define Credentials: Ensure that the credentials for the sender email are
defined correctly in your emailService. Replace "
***@***.***" and "YourPassword" with the actual sender's
email and password.

Authorization: Make sure the email account used has the necessary
permissions and is allowed to send emails programmatically.

Configuration: If you are using an email service provider (like Outlook),
check if there are any specific settings or API configurations required for
sending emails.
